### ISSUE TITLE
Require mic access before starting the demo or evolution

### ISSUE THREAD

**Issue by moseley** [ComTacTraining/ctt#98]
Before the demo or evolution is able to begin, the user must have granted permission to access the microphone. Sorting the mic before beginning the demo should help to aid the flow through the demo.

**Comment by moseley** [comment]
The video should not be able to begin unless the user has granted mic permissions or usingMic is set to false.

**Comment by justino2m** [comment]
I think the video can begin when users can't access the microphone or usingMic is set to false. There may be a scenario when users want to use only a keyboard, not a microphone.

If there is an issue with mic permission when usingMic is set to true, usingMic will be set automatically to false.  The user can send his command to the command center using the keyboard because he can't access the microphone.

Let me know if I miss anything.

**Comment by moseley** [comment]
usingMic is set to true by default. If the admin (keyboard is an admin only feature) toggles to keyboard mode, then usingMic is set to false. The video should be allowed to begin if usingMic is false or if the guest has granted mic permission. I believe the mic permission must be after an interaction so ideally it would happen when pressing the play button or clicking the video.
